//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsal_Gardent.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplyComment
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CommentID { get; set; }
        public string Answer { get; set; }
    
        public virtual AccCustomer AccCustomer { get; set; }
    }
}
